# Generated by Django 5.2.7 on 2025-10-14 11:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bufe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(default='Iskolai Büfé', max_length=100)),
                ('rendkivuli_zarva', models.BooleanField(default=False, verbose_name='Rendkívüli zárva')),
            ],
            options={
                'verbose_name': 'Büfé',
                'verbose_name_plural': 'Büfék',
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100, verbose_name='Név')),
                ('bufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategoriak', to='bufe.bufe', verbose_name='Büfé')),
            ],
            options={
                'verbose_name': 'Kategória',
                'verbose_name_plural': 'Kategóriák',
                'ordering': ['nev'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Hétfő'), (1, 'Kedd'), (2, 'Szerda'), (3, 'Csütörtök'), (4, 'Péntek'), (5, 'Szombat'), (6, 'Vasárnap')], verbose_name='Hét napja')),
                ('from_hour', models.TimeField(verbose_name='Nyitás')),
                ('to_hour', models.TimeField(verbose_name='Zárás')),
                ('bufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='bufe.bufe', verbose_name='Büfé')),
            ],
            options={
                'verbose_name': 'Nyitvatartás',
                'verbose_name_plural': 'Nyitvatartások',
                'ordering': ['weekday', 'from_hour'],
            },
        ),
        migrations.CreateModel(
            name='Rendeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(help_text='Rendelés tételei JSON formátumban', verbose_name='Tételek')),
                ('allapot', models.CharField(choices=[('leadva', 'Rendelés leadva'), ('visszavonva', 'Rendelés visszavonva'), ('visszaigasolva', 'Rendelés visszaigazolva'), ('torolve', 'Rendelés törölve'), ('atadva', 'Rendelés átadva')], default='leadva', max_length=20, verbose_name='Állapot')),
                ('leadva', models.DateTimeField(auto_now_add=True, verbose_name='Rendelés leadva')),
                ('idozitve', models.DateTimeField(blank=True, help_text='Időzítés - nyitvatartási időben csak, min. 10 perccel a rendelés leadása után', null=True, verbose_name='Időzítés')),
                ('megjegyzes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('archived', models.BooleanField(default=False, verbose_name='Archivált')),
                ('vegosszeg', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Végösszeg (Ft)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendelesek', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Rendelés',
                'verbose_name_plural': 'Rendelések',
                'ordering': ['-leadva'],
            },
        ),
        migrations.CreateModel(
            name='Termek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Név')),
                ('ar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ár (Ft)')),
                ('max_rendelesenkent', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max rendelésenkénti mennyiség')),
                ('hutve', models.BooleanField(default=False, verbose_name='Hűtve')),
                ('elerheto', models.BooleanField(default=True, verbose_name='Elérhető')),
                ('kisult', models.BooleanField(default=False, verbose_name='Kisült')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termekek', to='bufe.kategoria', verbose_name='Kategória')),
            ],
            options={
                'verbose_name': 'Termék',
                'verbose_name_plural': 'Termékek',
                'ordering': ['kategoria', 'nev'],
            },
        ),
    ]
