# Generated by Django 5.2.7 on 2025-10-14 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bufe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bufe',
            name='bufeadmin',
            field=models.ManyToManyField(blank=True, help_text='Felhasználók, akik kezelhetik a büfé rendeléseit', related_name='managed_bufes', to=settings.AUTH_USER_MODEL, verbose_name='Büfé adminisztrátorok'),
        ),
    ]
